* Dependencies
- quicklisp
- *sbcl* dependent
- portmidi - Download it locally
  - https://github.com/chfin/cl-portmidi
  - cd ~/quicklisp/local-projects
  - git clone https://github.com/chfin/cl-portmidi.git

* Setup
#+begin_src lisp
    (ql:quickload "ld-music")
    (in-package :ld-music)
#+end_src

#+RESULTS:
: #<PACKAGE "LD-MUSIC">

* Background
  #+begin_quote
  "This program is ugly, dirty, disgusting, not the way I would write this as a professional. It is written with concrete syntax, meaning I'm going to use lots of cars and cdrs..."
    -- Gerald Jay Sussman (https://youtu.be/aAlR3cezPJg?t=339)
  #+end_quote

This project is my exploration in representing musical information with LISP.

What kind of musical information is there to represent? To start... *Notes, Scales, and Chords.*

- *Notes* - the most basic unit of musical pitch information.
  These are currently represented as integers (MIDI) and symbolically as moveable-do solfege like (DO RE MI) and absolute name "C4" where "C" is the note and "4" is the octave on the keyboard.
- *Scales* - collections of notes based on scale patterns (major, minor, etc)
- *Chords* - collections of notes usually derived from a scale

This program deals only with the notes on a standard 88 key piano as limiting the notes to 88 seems to be practical at this time.

This project depends on the "portmidi" library to output midi to a hardware or software midi device of your choosing.

* High level ideas

  The piano is just a list of 88 notes.  From this fundamental
  structure we can derive all sorts of musical structures.

  I am personally interested in tonal structures such as the major and
  minor scales, diatonic chords derived from major/minor scales, and
  ear training concepts.

  In general, I want to create musical structures using commonly used
  symbols, the same symbols that used in music theory and ear
  training...

  Specifically, I want *solfege* symbols to represent notes, such as:
  
  - Ex.) The major scale in solfege: DO RE MI FA SO LA TI DO
  - Ex.) The nat. minor scale in solfege: DO RE ME FA SO SE LE TE DO
  - Ex.) The asc. chromatic scale: DO DI RE RI MI FA FI SO SI LA LI TI DO
  - Ex.) The desc. chromatic scale: DO TI TE LA LE SO SE FA MI ME RE RA DO

  Beyond solfege, I want to have symbols for referring to diatonic
  chords. In music theory and ear training chords are usually referred
  to by Roman Numerals:

  - Ex.) The most common chord progression: I V VI- IV
  - Ex.) The plagal cadence: I IV I
  - Ex.) The cycle V progression: I IV VII III- VI- III- V I

* MIDI Smoke testing
  
** List the midi devices available on your system:

  #+begin_src lisp  :package ld-music
    (pm:list-devices)
  #+end_src

  #+RESULTS:
  : ((0 . ALSA | Midi Through Port-0 | input: NIL | output: T) (1 . ALSA | Midi Through Port-0 | input: T | output: NIL) (2 . ALSA | Roland Digital Piano MIDI 1 | input: NIL | output: T) (3 . ALSA | Roland Digital Piano MIDI 1 | input: T | output: NIL))


  Find your MIDI device where output: T and copy the Integer.
  For example, my device is (2 . ALSA | Roland Digital Piano MIDI 1 | input: NIL | output: T)
  
** Initialize the midi device and smoke test
   
  #+begin_src lisp :package ld-music
    (pm-initialize 2)
  #+end_src

  #+RESULTS:
  : #.(SB-SYS:INT-SAP #X55AE35D700D0)

You should hear a note play when you run #'smoke-test.

  #+begin_src lisp :package ld-music
    (smoke-test)
  #+end_src

  #+RESULTS:
  : NIL

* DATA FORMATS

- NOTE -- an ALIST grouping TYPE, NAME, VALUE, SOLFEGE, OCTAVE
- SCALE -- an ALIST grouping NOTES and SCALE TEMPLATE
- SCALE TEMPLATE -- a list of scale steps/solfege pairs used to realize scales
  ((W . DO) (W . RE) (H . MI) (W . FA) (W . SO) (W . LA) (H . TI))
- CHORD -- a list of CHORD-TONES
- CHORD-TONE -- an ALIST grouping TYPE, NOTE, DEGREE
- SCALE-CHORD -- an ALIST grouping SCALE, CHORDS, ROMAN-NUMERAL-CHORDS 
- RHYTHMIC-NOTE -- a pairing of NOTE and RHYTHM-VALUE where RHYTHM-VALUE is 1,2,4,8,16
- EVENT -- an ALIST grouping NOTE, ON-TIME, OFF-TIME, VELOCITY

INTERNAL MAKER FUNCTIONS
#+begin_example
  (make-scale-template '(w w h w w w h) '(do re mi fa so la ti do))
  (make-note 'C4 72 'DO) 
  (make-scale-from-template 'C4 'C5 (major-scale-template))
  (make-scale scale-root template)
  (make-scale-chords scale)
  (make-chords start-note)
#+end_example

* Concepts
  
** Notes

A note is technically a frequency like "A 440HZ". But in this program a note is represented as an ALIST with following attributes:

#+begin_src lisp :package ld-music :exports both
(make-note 'A4 69 nil)
#+end_src

#+RESULTS:
: ((TYPE . NOTE) (NAME . A4) (VALUE . 69) (SOLFEGE) (OCTAVE . 4))

- TYPE -- The type of the object (NOTE)
- NAME -- The absolute name of the note on the keyboard
- VALUE -- The MIDI Value
- OCTAVE -- The keyboard octave
- SOLFEGE : The solfege syllable assigned to the note

*** Note functions

- make-note :: note constructor
- note-name :: note name selector
- note-value :: note midi value selector
- note-solfege :: note solfege syllable selector
- note-octave-up :: the note one octave up
- note-octave-down :: the note one octave down
- note-equal-p :: check for note equality matching *note-value* & *note-name*
- note-name-position :: position of note in scale (by name)
- note-idx :: note position in scale using #'note-equal-p
- parse-note-octave :: Parse octave of the note from the absolute name
- find-note-in-octave :: Find note in a scale sorted by octave relative to the scale (not absolute octaves)
  

** Scale templates

Scale templates are represented by a list of pairs (X,Y) where X is
either W or H and Y is a solfege syllable.

- W :: represents 1 semitone
- H :: represents 2 semitones

This data is used when building scales to assign the correct solfege
syllable to the note. 

#+begin_src lisp :package ld-music :exports both
(major-scale-template)
#+end_src

#+RESULTS:
: ((W . DO) (W . RE) (H . MI) (W . FA) (W . SO) (W . LA) (H . TI))

Making a scale template is done like so:

#+begin_src lisp :package ld-music :exports both
  (make-scale-template '(w w h w w w h)
		       '(do re mi fa so la ti do) )
#+end_src

#+RESULTS:
: ((W . DO) (W . RE) (H . MI) (W . FA) (W . SO) (W . LA) (H . TI))

Other scale templates are defined already:

- Chromatic scale template
  #+begin_src lisp :package ld-music :exports both
  (chromatic-scale-template)
  #+end_src

  #+RESULTS:
  : ((H . DO) (H DI RA) (H . RE) (H RI ME) (H . MI) (H . FA) (H FI SE) (H . SO) (H SI LE) (H . LA) (H LI TE) (H . TI))

- Minor scale template
  #+begin_src lisp :package ld-music :exports both
    (minor-scale-template)
  #+end_src

  #+RESULTS:
  : ((W . DO) (H . RE) (W . ME) (W . FA) (H . SO) (W . LE) (W . TE))

- Dorian scale template
  #+begin_src lisp :package ld-music :exports both
    (make-scale-template '(w h w w w h w) '(do re me fa so la ti do))
  #+end_src

  #+RESULTS:
  : ((W . DO) (H . RE) (W . ME) (W . FA) (W . SO) (H . LA) (W . TI))

*** Scale functions

** Scales

Scales are represented as ALISTS containing NOTES and a TEMPLATE.

** Chord

** Chord Tones

** Scale Chords

* Data and Functions

The initial and most fundamental data we have is a list of MIDI INTEGERS (21..108)

#+begin_src lisp :package ld-music
  (midi-integers)
#+end_src

#+RESULTS:
| 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 76 | 77 | 78 | 79 | 80 | 81 | 82 | 83 | 84 | 85 | 86 | 87 | 88 | 89 | 90 | 91 | 92 | 93 | 94 | 95 | 96 | 97 | 98 | 99 | 100 | 101 | 102 | 103 | 104 | 105 | 106 | 107 | 108 |

Then there is the #'midi-note-octave list of absolute note names and octave

 #+begin_src lisp :package ld-music
   (midi-note-octave)
 #+end_src

 #+RESULTS:
 : (A0 |A#0| B0 C0 |C#0| D0 |D#0| E0 F0 |F#0| G0 |G#0| A1 |A#1| B1 C1 |C#1| D1
 :  |D#1| E1 F1 |F#1| G1 |G#1| A2 |A#2| B2 C2 |C#2| D2 |D#2| E2 F2 |F#2| G2 |G#2|
 :  A3 |A#3| B3 C3 |C#3| D3 |D#3| E3 F3 |F#3| G3 |G#3| A4 |A#4| B4 C4 |C#4| D4
 :  |D#4| E4 F4 |F#4| G4 |G#4| A5 |A#5| B5 C5 |C#5| D5 |D#5| E5 F5 |F#5| G5 |G#5|
 :  A6 |A#6| B6 C6 |C#6| D6 |D#6| E6 F6 |F#6| G6 |G#6| A7 |A#7| B7 C7)

 #+begin_src lisp  :package ld-music
   (first (midi-note-octave)) ; A0
   (last (midi-note-octave))  ; (C7)
   (length (midi-note-octave)); 88
 #+end_src

The  #'midi-notes function turns the MIDI integers and absolute note names into the NOTE data structure

#+begin_src lisp  :package ld-music
  (first (midi-notes)); ((TYPE . NOTE) (NAME . A0) (VALUE . 21) (SOLFEGE) (OCTAVE . 0))
  (last (midi-notes)); (((TYPE . NOTE) (NAME . C7) (VALUE . 108) (SOLFEGE) (OCTAVE . 7))) 
  (length (midi-notes)); 88
#+end_src

At this point, we have a basic representation of all notes on the keyboard.
The next step is to build scales.

*Scale templates* are used to realize scales from the patterns they
define. For example, The major scale uses a pattern of "W W H W W W H"
where W is 2 semitones and H is 1 semitone.

The #'make-scale-template function is used to make *scale templates*.

To define the major scale template, set the pattern and the solfege
syllables:

#+begin_src lisp  :package ld-music
  (make-scale-template '(w w h w w w h) '(do re mi fa so la ti do))
#+end_src

#+RESULTS:
: ((W . DO) (W . RE) (H . MI) (W . FA) (W . SO) (W . LA) (H . TI))

To realize the scale, use the *#'make-scale-from-template* function.

The algorithm looks at all notes available and returns only the notes
found according to the scale pattern.

The function signature requires a starting note and end note.

To creates a C major scale from C4 to C5:
#+begin_src lisp  :package ld-music
  (let ((major-scale-template
	  (make-scale-template '(w w h w w w h)
			       '(do re mi fa so la ti do))))
    (make-scale-from-template 'C4 'C5 major-scale-template))
#+end_src

#+RESULTS:
| (TYPE . NOTE) | (NAME . C4) | (VALUE . 72) | (SOLFEGE . DO) | (OCTAVE . 4) |
| (TYPE . NOTE) | (NAME . D4) | (VALUE . 74) | (SOLFEGE . RE) | (OCTAVE . 4) |
| (TYPE . NOTE) | (NAME . E4) | (VALUE . 76) | (SOLFEGE . MI) | (OCTAVE . 4) |
| (TYPE . NOTE) | (NAME . F4) | (VALUE . 77) | (SOLFEGE . FA) | (OCTAVE . 4) |
| (TYPE . NOTE) | (NAME . G4) | (VALUE . 79) | (SOLFEGE . SO) | (OCTAVE . 4) |
| (TYPE . NOTE) | (NAME . A5) | (VALUE . 81) | (SOLFEGE . LA) | (OCTAVE . 5) |
| (TYPE . NOTE) | (NAME . B5) | (VALUE . 83) | (SOLFEGE . TI) | (OCTAVE . 5) |
| (TYPE . NOTE) | (NAME . C5) | (VALUE . 84) | (SOLFEGE . DO) | (OCTAVE . 5) |

Each item in the list is a NOTE -- an ALIST representing SOLFEGENAME,
NOTENAME, MIDI-VALUE, and KEYBOARD OCTAVE.

The functions #'note-name, #'note-value, #'note-solfege are used to
select note data.

** CHORDS
The next logical step would be to build up chords.

The C Major scale notes are C D E F G A B. To make chords, you combine every other note in scale:

The triads in C major are "CEG" "DFA" "EGB" "FAC" "GBD" "ACE" "BDF".

The seventh chords in C major are "CEGA" "DFAG" "EGBD" "FACE" "GBDF" "ACEG" "BDFA".

Use the #'chord-builder function to generate a list of chords.

*#'chord-builder* takes a scale and generates a list of chords up the
the 13th (remember, a chord is just a list of notes)

#+begin_src lisp :package ld-music
  (take 7 (let* ((c-major-scale
	   (make-scale-from-template 'C2 'G4
				     (make-scale-template '(w w h w w w h)
							  '(do re mi fa so la ti do)))))
    (chord-builder c-major-scale)))
#+end_src

#+RESULTS:
| ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . C2) (VALUE . 48) (SOLFEGE . DO) (OCTAVE . 2)) (DEGREE . 1)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . E2) (VALUE . 52) (SOLFEGE . MI) (OCTAVE . 2)) (DEGREE . 3)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . G2) (VALUE . 55) (SOLFEGE . SO) (OCTAVE . 2)) (DEGREE . 5)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . B3) (VALUE . 59) (SOLFEGE . TI) (OCTAVE . 3)) (DEGREE . 7)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . D3) (VALUE . 62) (SOLFEGE . RE) (OCTAVE . 3)) (DEGREE . 9)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . F3) (VALUE . 65) (SOLFEGE . FA) (OCTAVE . 3)) (DEGREE . 11)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . A4) (VALUE . 69) (SOLFEGE . LA) (OCTAVE . 4)) (DEGREE . 13)) |
| ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . D2) (VALUE . 50) (SOLFEGE . RE) (OCTAVE . 2)) (DEGREE . 1)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . F2) (VALUE . 53) (SOLFEGE . FA) (OCTAVE . 2)) (DEGREE . 3)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . A3) (VALUE . 57) (SOLFEGE . LA) (OCTAVE . 3)) (DEGREE . 5)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . C3) (VALUE . 60) (SOLFEGE . DO) (OCTAVE . 3)) (DEGREE . 7)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . E3) (VALUE . 64) (SOLFEGE . MI) (OCTAVE . 3)) (DEGREE . 9)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . G3) (VALUE . 67) (SOLFEGE . SO) (OCTAVE . 3)) (DEGREE . 11)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . B4) (VALUE . 71) (SOLFEGE . TI) (OCTAVE . 4)) (DEGREE . 13)) |
| ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . E2) (VALUE . 52) (SOLFEGE . MI) (OCTAVE . 2)) (DEGREE . 1)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . G2) (VALUE . 55) (SOLFEGE . SO) (OCTAVE . 2)) (DEGREE . 3)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . B3) (VALUE . 59) (SOLFEGE . TI) (OCTAVE . 3)) (DEGREE . 5)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . D3) (VALUE . 62) (SOLFEGE . RE) (OCTAVE . 3)) (DEGREE . 7)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . F3) (VALUE . 65) (SOLFEGE . FA) (OCTAVE . 3)) (DEGREE . 9)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . A4) (VALUE . 69) (SOLFEGE . LA) (OCTAVE . 4)) (DEGREE . 11)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . C4) (VALUE . 72) (SOLFEGE . DO) (OCTAVE . 4)) (DEGREE . 13)) |
| ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . F2) (VALUE . 53) (SOLFEGE . FA) (OCTAVE . 2)) (DEGREE . 1)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . A3) (VALUE . 57) (SOLFEGE . LA) (OCTAVE . 3)) (DEGREE . 3)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . C3) (VALUE . 60) (SOLFEGE . DO) (OCTAVE . 3)) (DEGREE . 5)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . E3) (VALUE . 64) (SOLFEGE . MI) (OCTAVE . 3)) (DEGREE . 7)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . G3) (VALUE . 67) (SOLFEGE . SO) (OCTAVE . 3)) (DEGREE . 9)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . B4) (VALUE . 71) (SOLFEGE . TI) (OCTAVE . 4)) (DEGREE . 11)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . D4) (VALUE . 74) (SOLFEGE . RE) (OCTAVE . 4)) (DEGREE . 13)) |
| ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . G2) (VALUE . 55) (SOLFEGE . SO) (OCTAVE . 2)) (DEGREE . 1)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . B3) (VALUE . 59) (SOLFEGE . TI) (OCTAVE . 3)) (DEGREE . 3)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . D3) (VALUE . 62) (SOLFEGE . RE) (OCTAVE . 3)) (DEGREE . 5)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . F3) (VALUE . 65) (SOLFEGE . FA) (OCTAVE . 3)) (DEGREE . 7)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . A4) (VALUE . 69) (SOLFEGE . LA) (OCTAVE . 4)) (DEGREE . 9)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . C4) (VALUE . 72) (SOLFEGE . DO) (OCTAVE . 4)) (DEGREE . 11)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . E4) (VALUE . 76) (SOLFEGE . MI) (OCTAVE . 4)) (DEGREE . 13)) |
| ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . A3) (VALUE . 57) (SOLFEGE . LA) (OCTAVE . 3)) (DEGREE . 1)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . C3) (VALUE . 60) (SOLFEGE . DO) (OCTAVE . 3)) (DEGREE . 3)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . E3) (VALUE . 64) (SOLFEGE . MI) (OCTAVE . 3)) (DEGREE . 5)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . G3) (VALUE . 67) (SOLFEGE . SO) (OCTAVE . 3)) (DEGREE . 7)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . B4) (VALUE . 71) (SOLFEGE . TI) (OCTAVE . 4)) (DEGREE . 9)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . D4) (VALUE . 74) (SOLFEGE . RE) (OCTAVE . 4)) (DEGREE . 11)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . F4) (VALUE . 77) (SOLFEGE . FA) (OCTAVE . 4)) (DEGREE . 13)) |
| ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . B3) (VALUE . 59) (SOLFEGE . TI) (OCTAVE . 3)) (DEGREE . 1)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . D3) (VALUE . 62) (SOLFEGE . RE) (OCTAVE . 3)) (DEGREE . 3)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . F3) (VALUE . 65) (SOLFEGE . FA) (OCTAVE . 3)) (DEGREE . 5)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . A4) (VALUE . 69) (SOLFEGE . LA) (OCTAVE . 4)) (DEGREE . 7)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . C4) (VALUE . 72) (SOLFEGE . DO) (OCTAVE . 4)) (DEGREE . 9)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . E4) (VALUE . 76) (SOLFEGE . MI) (OCTAVE . 4)) (DEGREE . 11)) | ((TYPE . CHORD-TONE) (NOTE (TYPE . NOTE) (NAME . G4) (VALUE . 79) (SOLFEGE . SO) (OCTAVE . 4)) (DEGREE . 13)) |

*** Triads and Sevenths
The *#'triads* and *#'sevenths* functions take a list of chords and reduce
each chord to a specific number of notes, 3 and 4 respectively.

The *#'chord-take function* takes an integer and list of chords and returns a shortened list.

#+begin_example
  (car (triads (test-chord-builder))) 
#+end_example
: => (((C2 . 48) . DO) ((E2 . 52) . MI) ((G2. 55) . SO))

#+begin_example
  (car (sevenths (test-chord-builder)))
#+end_example
: => (((C2 . 48) . DO) ((E2 . 52) . MI) ((G2 . 55) . SO) ((B3 . 59) . TI)) 

#+begin_example
(car (chord-take 2 (test-chord-builder)))
#+end_example
: => (((C2 . 48) . DO) ((E2 . 52) . MI))

* Upcoming documentation
** additional chord functions inversions

      #+begin_example
   (defun inversion-test ()
     (chord-play (car (triads (chord-builder (scale-range 'C3 'G5 (make-scale 'c4))))))

     (chord-play (chord-over-3 (car (triads (chord-builder (scale-range 'C3 'G5 (make-scale 'c4)))))  (make-scale 'c4)))

     (chord-play (chord-over-5 (car (triads (chord-builder (scale-range 'C3 'G5 (make-scale 'c4))))) (make-scale 'c4)))

     (chord-play (car (triads (chord-builder (scale-range 'C4 'G5 (make-scale 'c4))))))

     )

    (mapcar #'chord-play (take 8 (triads (modes2 (make-scale-from-template 'C2 'B5 (major-scale-template))))))

   (chord-play (chord-invert (car (chords (scale-range 'c3 'G5 (make-scale 'c4)))) (make-scale 'c4)))

   (chord-invert (chord-remove-degree (chord-upper (car (cdr (chords (scale-range 'c3 'G5 (make-scale 'c4)) #'sevenths)))) 5) (make-scale 'c4))
      #+end_example

** with-scale macro

   #+begin_example
     (with-scale (random-major-scale)
       (play-scale *current-scale*))

     (with-scale (random-major-scale)
       (play-tonic-subdominant-dominant  *current-scale*))

     (with-scale (random-major-scale)
       (play-tonic *current-scale*)
       (sleep 0.5)
       (play-subdominant *current-scale*)
       (sleep 0.5)
       (play-dominant *current-scale*)
       (sleep 0.5)
       (play-tonic *current-scale*))

     (with-scale (random-major-scale)
       (solfege-chord '(DO MI SO) *current-scale*))

     (with-scale (random-major-scale)
       (play-tonic-subdominant-dominant *current-scale*))

     (with-scale (random-major-scale)
       (chord-builder *current-scale*))

     (mapcar #'chord-play (triads (chord-builder (build-scale 'C4 (major-scale-template)))))
     (mapcar #'chord-play (subseq (triads (chord-builder (build-scale 'C4 (major-scale-template)))) 16 24))

   #+end_example

** Chord sequencing
   #+begin_example
     (with-scale (build-scale 'C4 (major-scale-template))
       (play-chords (sevenths (chord-sequence '(I IV V I)
					      (scale-range 'C2 'G3 *current-scale*)))))

     (with-scale (build-scale 'C4 (major-scale-template))
       (let* ((chord-list (take-octaves 2 (chord-builder (scale-range 'A2 'C7 *current-scale*))))
	      (chords (chord-roman-numerals (triads chord-list)))
	      (chord-sequence '(I VI- II- V III- VI- II- V I)))

	 (play-chords (mapcar (lambda (rn)
				(find-chord rn chords))
			      chord-sequence))))

     (chord-sequence-play
      (chord-sequence-chords
       (chord-sequence
	'((octave . 3) I (octave . 3) VI- (octave . 3)  II- (octave . 2) V (octave . 3) I)
	(chords (make-scale 'C4) #'sevenths))))
   
     (chords (make-scale 'C4) #'sevenths)

   #+end_example

** Solfege chords
   #+begin_example
     (with-scale (scale-range 'C4 'G5 (make-scale 'C4))
      (solfege-chord '(Do mi so) *current-scale*)
      (solfege-chord '(re fa la) *current-scale*)
      (solfege-chord '(mi so ti) *current-scale*)
      (arp '(do mi so) *current-scale*)
      (rarp '(do mi so) *current-scale*))

   #+end_example

** Threading function
   #+begin_example
     (-> (make-scale-chords (make-scale 'C2))
	 (scale-chord-filter #'chord-type-filter #'ninths)
	 (scale-chord-filter #'chord-filter #'chord-butfifth)
	 (scale-chord-filter #'chord-filter #'chord-droproot)
	 (chord-seq '(II-
		      (octave . 2)
		      V
		      (octave . 3)
		      I
		      (octave . 3)
		      VI-
		      (octave . 3)
		      II-
		      (octave . 2)
		      V
		      (octave . 3)
		      I
		      I
		      ) 3))

	   #'chord-seq-play)
   #+end_example

** Games
   
*** Solfege trainer

*** Melody Game

*** Bass Game

** MIDI functions

- program-change ::
- note-play ::
- note-off ::
- note-play-sleep ::
- make-message ::
- make-message* ::
- midi-notes ::
- midi-integers ::
- midi-instruments ::
- pm-initialize ::
- pm-terminate ::
- pm-reload :: 

** Chord functions
- find-chord (octave romand-num chord-list scale) ::
- make-chord-tone (note degree) ::
- chord-tone-note (chord-tone)(attr 'note chord-tone)) ::
- chord-degree (chord-tone) (attr 'degree chord-tone)) ::
- chord-notes (chord) (mapcar #'chord-tone-note chord)) ::
- chord-builder (l) ::
- make-chords (start-note &optional (filter-fn #'triads) (template (major-scale-template))) ::
- make-scale-chords (scale) ::
- scale-chords (scale-chord-data) (attr 'chords scale-chord-data)) ::
- chord-sequence-chords (chord-sequence) (mapcdr chord-sequence)) ::
- chord-root (chord) ::
- chord-sequence-play (chord-sequence &optional (sleep 1)) ::
- chord-butroot (chord) (chord-remove-degree chord 1)) ::
- chord-butfifth (chord) (chord-remove-degree chord 5)) ::
- chord-drop-root (chord)  ::
- chord-invert-upper (chord) ::
- chord-tone-degree (chord-tone) (attr 'degree chord-tone)) ::
- chord-remove-degree (chord degree) ::
- chord-take (n listofchords) ::
- triads (myl) (chord-take 3 myl)) ::
- sevenths (myl) (chord-take 4 myl)) ::
- ninths (myl) (chord-take 5 myl)) ::
- elevenths (myl) (chord-take 6 myl)) ::
- thirteenths (myl) (chord-take 7 myl)) ::
- chord-invert (chord scale) ::
- chord-over-3 (root-position-chord scale) ::
- chord-over-5 (root-position-chord scale) ::
- major-solfege-chords () ::
- chord-roman-numerals (chord-list) ::
- chord-sequence (chord-sequence chords scale &optional (octave 4)) ::
- scale-chord-filter (fn &rest args) ::
- rebuild-chords () ::
- octave-filter (octave) ::
- chord-filter (fn) ::
- chord-type-filter (fn) ::
- chord-seq (seq &optional (octave 4)) ::

** Scale functions
- make-scale-template (steps solfege) ::
- chromatic-scale-template () ::
- major-scale-template () (make-scale-template '(w w h w w w h) '(do re mi fa so la ti) )) ::
- minor-scale-template () (make-scale-template '(w h w w h w w) '(do re me fa so le te))) ::
- dorian-scale-template () (make-scale-template '(w h w w w h w) '(do re me fa so la ti))) ::
- phrygian-scale-template () (make-scale-template '(h w w w h w) '(do ra me fa so le te))) ::
- scale-range (n1 n2 scale) ::
- make-scale-from-template (p1 p2 scale-template) ::
- build-scale-up (from-note-pos pattern) ::
- build-scale-down (from-note-pos pattern) ::
- assign-solfege (scale scale-template) ::
- build-scale (start-note pattern &optional (notes (midi-notes))) ::
- random-scale (template) ::
- random-scale2 (template) ::
- random-major-scale () (random-scale (major-scale-template))) ::
- random-major-scale2 () (random-scale2 (major-scale-template))) ::
- random-chromatic-scale () (random-scale2 (chromatic-scale-template ))) ::
- scale-notes (scale) ::
- make-scale (scale-root &optional (template (major-scale-template))) ::
- scale-range2 (p1 p2 scale-data) ::
- scale-octaves (scale &optional (count 0)) ::
- midi-notes-from-scale (midi-notes original-scale scale) ::
- midi-notes-from-scale-down-helper (midi-notes original-scale scale) ::
- with-scale-helper (scale my-fn) ::
- random-note (scale) (nth (random (length scale)) scale)) ::
- random-notes (y scale) (loop for x from 1 to y collect (random-note scale))) ::
- solfege-chord (l scale) ::
- find-solfege (solfege lis) ::
- major-scales () ::
- spell-scale (root) ::

* Files
** package
- Defines the package and exports
** random
Generating random notes and functions for use with games
-      3:(defun find-prev-do-helper (idx scale)
-      8:(defun find-prev-do (note scale)
-     13:(defun resolve-down (note scale)
-     22:(defun resolve-note (note scale)
-     29:(defun note-to-do (note scale)
-     37:(defun remove-after-do (scale)
-     44:(defun random-notes ()
-     60:(defun random-chromatic ()
-     91:(defun scale-octave-range-helper (o1 o2 scale)
-     98:(defun scale-octave-range (o1 o2 notes)
-    104:(defun play-tonic-subdominant-dominant2 (scale)
-    108:(defun play-tonic-subdominant-dominant3 (scale)
-    112:(defun sing-do ()
-    120:(defun random-chromatic2 ()
-    163:(defun random-chromatic3 ()
-    201:(defun notes->midi ()

** output.lisp
- Should be taken out of this library.
** util
- Utility functions
** midi
- Lower-level midi functions
** chord
- chord representation and functions
** note
- note representation and functions
** scale
- note representation and functions
** play
- functions for playing notes
** games
- logic/functions to support games
** sequencer
- logic for generating/writing midi sequences to file
- logic for generating midi sequences for portmidi

* Issues
  - setting slot-value 'midi:dd/nn/cc/bb doesn't work out of the box
    because not exported. had to fork cl-midi library and add exports
  - update local cl-portmidi library to get updates and remove
    make-message* fns as make-message now exported
  - work on setting up exports in ASD file
  - should every file be in the same namespace?
